# Generated by Django 3.2.3 on 2021-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistingpage',
            old_name='headline_text',
            new_name='headline_text1',
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='headline_text2',
            field=models.CharField(blank=True, help_text='Blog listing page header text.', max_length=70),
        ),
    ]
