# Generated by Django 3.2.3 on 2021-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210601_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='headline_subtitle',
            field=models.CharField(blank=True, help_text='Blog listing page header subtitle.', max_length=150),
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='headline_text1',
            field=models.CharField(blank=True, help_text='Blog listing page header text first line.', max_length=70),
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='headline_text2',
            field=models.CharField(blank=True, help_text='Blog listing page header text second line.', max_length=70),
        ),
    ]
