# Generated by Django 3.2.3 on 2021-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_hero_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_title',
            new_name='hero_title1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title2',
            field=models.CharField(blank=True, help_text='Main text displayed in the hero section over the background.', max_length=120),
        ),
    ]
